### ISSUE TITLE
ENH+REVIEW: Enhancement for filter reads actions (for single-end and paired-end reads)

### ISSUE THREAD

**Issue by ChristosMatzoros** [bokulich-lab/q2-minimap2#15]
The code and execution of the actions `filter_paired_end_reads` and `filter_single_end_reads` needs additional review to detect potential enhancements or bugs.

The `filter_paired_end_reads` action aligns paired-end reads to a reference genome or index using Minimap2, processes the alignment to filter out reads based on the specified percentage identity and either keeps the mapped or the unmapped sequences based on what the user specifies. It modifies flags for paired and unmapped reads appropriately in order to be recognized by the samtools fastq command which converts the filtered alignments into separate FASTQ files for each read in the pair. This allows users to handle paired-end sequencing data specifically, ensuring the reads are appropriately paired and filtered.

The `filter_single_end_reads` function performs a similar process but for single-end reads. It aligns these reads to a reference genome, filters the alignments based on identity and either keeps the mapped or the unmapped sequences based on what the user specifies. Then it converts the filtered alignments into initial FASTQ format. This function is tailored for single-end reads, focusing on filtering individual reads without considering pair relationships.

**Comment by VinzentRisch** [comment]
See some suggestions below. I will run the functions when you have implemented the changes. 👍

_minimap2_filter_single_end_reads
- convert sam file to fastqfile directly 

filter_single_end_reads
- n_threads: int = 4, check what minimap uses and use that as default
- "matching_score": Int,  "mismatching_penalty": Int, can these two parameters really be any int also 0 and negative numbers?


build_filtered_out_dir
- has an unused parameter called input_df. You are acctually giving these parameters when calling the function but it is not used in the function. If you dont use it then you can also remove the input_df = query_reads.manifest.view(pd.DataFrame) from filter_paired_end_reads and filter_single_end_reads
- you can remove the path variables and do directly: 
  ```
  shutil.copy(os.path.join(filtered_seqs.path, filename), input_reads.path)
```
because if the filename does not change while copying you dont have to specify it again
- There is no test for this function, please add one  

set_penalties
- i would call these parameters not (match, mismatch, gap_o, gap_e) but there full names that you use everywhere else matching_score, mismatching_penalty, gap_open_penalty, gap_extension_penalty to avoid confusion
- for if gap_o is not None: and if gap_e is not None: you can just do if gap_e: because you are sure that they cant be 0. I dont know if match can be 0 so there you have to leave it like this.

convert_to_fastq_single
- what is the purpose of str(n_threads - 1)? What happens if threads is set to 1 and this calculates to threads 0? same also in convert_to_fasta and convert_to_fastq_paired and make_samt_cmd

_minimap2_filter_paired_end_reads
- same as _minimap2_filter_single_end_reads  you can convert sam to fastq directly

make_mn2_cmd and make_mn2_paired_end_cmd
- adding minimap2_cmd += [reads1, reads2]  minimap2_cmd += ["-o", samf_fp] at the end looks ugly maybe it is possible to take it into the normal command and add the penalties at the end

process_sam_file
- you open the tmpfile to close it again and then to open it again for writing you can just open it once the second time is unnecessary. just put the tmp file and the sam file in the same with statement

Maybe consider using pysam in the future its a wrap for the samtools package. That would remove all the functions that are just there to create a samtools command
